### ISSUE TITLE
[Request] Most common patch format (small size)

### ISSUE THREAD

**Issue by KaroNiko** [fcolecumberri/Doddler_Bizarre_Adventure_in_the_Matriarchy#6]
Hi pal. Couldn't you release the next patches in xdelta or similar format? These available now are cumbersome (big size) to download every time, and then they contain copyrighted material, and this could bring future problems towards you. Good job perfecting this translation! Greetings.

**Comment by fcolecumberri** [comment]
About the Copyright, That is the reason I only release the parts that got modified. I doubt I could get in trouble since you still need to have a legal copy of the game for the rest of the files and I have been very emphatic about buying it.

If AliceSoft ask me to stop, I will nuke the entire repo, no questions ask. However, AliceSoft has not been aggressive to translation/mod projects in the past, I doubt they will in the future.

Also usually the amount of trouble Copyright infringement generates is proportionally to the comercial/economic impact the operation has (I know this change from country to country). I doubt there has been people who stopped buying the game because of this project (specially when this project was born 20+ years after the game got release).

About the xdelta, that's actually a good idea, I might do that, I just need to incorporate it into my recompilation python script.
